### ISSUE TITLE
Updates ToDo

### ISSUE THREAD

**Issue by mjh16** [mjh16/academic#13]
- [x] Update Talks
    - [ ] SAMLA
    - [ ] YAH
    - [ ] Talk To Yancey's Class
- [ ] Include Service Section
    - [ ] Include GESO
    - [ ] GAU Bargaining
    - [ ] GAU Rep Stuff
    - [ ] College Comp Committee
- [ ] Academics
    - [ ] Classes Taken and Major Projects
    - [ ] Dr. Graban, Committee, Speciality and Minor Areas
- [ ] Research 
    - [ ] IRB research
- [ ] Publications
    - [ ] As I get stuff, put it up
